# From https://github.com/oklog/oklog/wiki/Integrations
# Run a logspout service on each node, and send the data to the oklog-ingest service.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logspout
spec:
  template:
    metadata:
      labels:
        app: logspout
    spec:
      hostPID: true
      hostIPC: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          env:
            - name: ROUTE_URIS
              value: raw+tcp://oklog.default.svc.cluster.local:7651
          image: gliderlabs/logspout:v3.1
          name: logspout
          volumeMounts:
            - name: log
              mountPath: /var/run/docker.sock
      volumes:
        - name: log
          hostPath:
              path: /var/run/docker.sock
